name: template-env
channels:
  - defaults
  - conda-forge
dependencies:
  - black
  - python
  - cookiecutter
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pre-commit
  - pip
  - pytest
  - python-dotenv
  - scipy
  - scikit-learn
  - seaborn
  - statsmodels
  - tensorflow
  - pip:
